pipeline{
    agent any
    stages {
        stage('Checkout git'){
            steps{
                git poll: true, url: 'https://github.com/sha5823/Sharon.git'
            }
        }

        stage('AnalysisSonarQube'){
            steps{
                withSonarQubeEnv('SonarQubeLocal'){
                    dir('demo'){
                        bat 'gradlew.bat sonarqube'
                    }
                }
            }
        }
        stage('Checking project status'){
            steps{
                dir('demo'){
                    bat 'gradlew.bat checkSonarQube'
                }
            }
        }

        stage('Project Clean'){
            steps{
                dir('demo') { bat 'gradlew.bat clean' }
            }
        }

        stage('Project Build'){
            steps{
                dir('demo') { bat 'gradlew.bat build' }
            }
        }

    }
}
