pipeline{
    agent any
    stages {
        stage('Checkout-git'){
            steps{
                git poll: true, url: 'https://github.com/sha5823/Sharon.git'
            }
        }

        stage('AnalysisSonarQube'){
            steps{
                withSonarQubeEnv('SonarQubeLocal'){
                    bat './gradew sonarqube'
                }
            }
        }

        stage('Project-Clean'){
            steps{
                dir('demo') { bat 'gradlew.bat clean' }
            }
        }

        stage('Project-Build'){
            steps{
                dir('demo') { bat 'gradlew.bat build' }
            }
        }

    }
}
